version: '3.8'

services:
  node1:
    build: .
    container_name: node1
    volumes:
      - ./source:/home/developer/source
    tty: true
    stdin_open: true
    networks:
      chat_net:
        ipv4_address: 10.100.0.10

  node2:
    build: .
    container_name: node2
    volumes:
      - ./source:/home/developer/source
    tty: true
    stdin_open: true
    networks:
      chat_net:
        ipv4_address: 10.100.0.20

networks:
  chat_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/24